"""initial

Revision ID: 04d070af22df
Revises: 
Create Date: 2026-05-10 22:46:12.854434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d070af22df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carteras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carteras_id'), 'carteras', ['id'], unique=False)
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrumentos_id'), 'instrumentos', ['id'], unique=False)
    op.create_index(op.f('ix_instrumentos_isin'), 'instrumentos', ['isin'], unique=True)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartera_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('comision', sa.Float(), nullable=True),
    sa.Column('tipo_cambio', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cartera_id'], ['carteras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_instrumentos_isin'), table_name='instrumentos')
    op.drop_index(op.f('ix_instrumentos_id'), table_name='instrumentos')
    op.drop_table('instrumentos')
    op.drop_index(op.f('ix_carteras_id'), table_name='carteras')
    op.drop_table('carteras')
    # ### end Alembic commands ###
